apiVersion: v1
kind: Secret
metadata:
  name: airflow-image-pull-secret
  namespace: airflow
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: |
      {
          "auths": {
              "ghcr.io": {
                  "username": "johnstonmatt",
                  "password": "ghp_foo,
                  "email": "matt.johnston@polyseam.io",
                  "auth": "am9obnN0b25tYXR0OmdocF9mb28="
              }
          }
      }
