apiVersion: v1
kind: Secret
metadata:
  name: airflow-image-pull-secret
  namespace: airflow
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: $cndi_on_ow.seal_secret_from_env_var(AIRFLOW_IMAGE_REGISTRY_CREDS)

